Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"
    vm1.vm.network "private_network", ip: "10.9.8.5"
  end
  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: "10.9.8.6"
  end
end
